// Auto-generated by: npx supabase gen types typescript --project-id <id>
// This is a representative hand-authored version; regenerate after migrations.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          stripe_price_id: string | null
          subscription_status: 'free' | 'active' | 'past_due' | 'canceled' | 'trialing'
          subscription_period_end: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          subscription_status?: 'free' | 'active' | 'past_due' | 'canceled' | 'trialing'
          subscription_period_end?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      sessions: {
        Row: {
          id: string
          user_id: string
          title: string
          started_at: string
          in_amount: number
          out_amount: number
          notes: string | null
          tags: string[]
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          started_at: string
          in_amount?: number
          out_amount?: number
          notes?: string | null
          tags?: string[]
          created_at?: string
          updated_at?: string
        }
        Update: Partial<Database['public']['Tables']['sessions']['Insert']>
      }
      audit_log: {
        Row: {
          id: number
          user_id: string | null
          action: string
          resource: string
          resource_id: string | null
          meta: Json | null
          created_at: string
        }
        Insert: {
          user_id?: string | null
          action: string
          resource: string
          resource_id?: string | null
          meta?: Json | null
          created_at?: string
        }
        Update: never
      }
    }
    Functions: {
      is_pro: {
        Args: { uid?: string }
        Returns: boolean
      }
    }
    Enums: {}
  }
}
